import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Layout } from 'components/Layout'
import { PostCard, PostDataType } from 'components/PostCard'
import { getAllMDXFiles, pageSlug } from './[...slug]'
import { serialize } from 'next-mdx-remote/serialize'

export const getStaticProps: GetStaticProps = async () => {
  console.log('1:', 1)
  const fg = require('fast-glob')
  const fs = require('fs')
  const pages = await getAllMDXFiles(fg)
  console.log('pages:', pages)
  const posts: Array<PostDataType> = []
  for (const page of pages) {
    const data = fs.readFileSync(page.toString())
    const mdxSource = await serialize(data.toString(), {
      parseFrontmatter: true,
    })
    const { frontmatter } = mdxSource

    const slug = pageSlug(page)

    // @ts-ignore
    posts.push({
      ...frontmatter,
      path: `/blog/${pageSlug(page)}`,
      image: frontmatter?.featuredImage || null, // Can't be undefined
      slug,
    })
  }

  console.log('posts:', posts)
  return {
    props: { posts },
  }
}

type HomeProps = {
  posts: Array<PostDataType>
}

const Home: NextPage<HomeProps> = ({ posts }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="bg-gray-50">
          <div className="content">
            <ol
              className="grid gap-4 p-8"
              style={{
                gridTemplateColumns: 'repeat(auto-fit, minmax(18rem, 1fr))',
              }}
            >
              {posts.map((post: PostDataType, i) => (
                <PostCard key={i} post={post} />
              ))}
            </ol>
          </div>
        </div>
      </Layout>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
