import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Layout } from 'components/Layout'
import { PostCard, PostDataType } from 'components/PostCard'
import { getAllMDXFiles, pageSlug } from './[...slug]'
import { serialize } from 'next-mdx-remote/serialize'

export const getStaticProps: GetStaticProps = async () => {
  const fg = require('fast-glob')
  const fs = require('fs')
  const pages = await getAllMDXFiles(fg)
  let posts: Array<PostDataType> = []
  for (const page of pages) {
    const data = fs.readFileSync(page.toString())
    const mdxSource = await serialize(data.toString(), {
      parseFrontmatter: true,
    })
    const { frontmatter } = mdxSource

    const slug = pageSlug(page)

    // @ts-ignore
    posts.push({
      ...frontmatter,
      path: `/blog/${pageSlug(page)}`,
      image: frontmatter?.featuredImage || null, // Can't be undefined
      slug,
    })
  }
  posts = posts.filter((post) => !post?.draft)
  posts = posts.sort((post1, post2) => (post2?.date > post1?.date ? 1 : -1))

  return {
    props: { posts},
  }
}

type HomeProps = {
  posts: Array<PostDataType>
}

const Home: NextPage<HomeProps> = ({ posts }) => {
  const newestIndex = posts.findIndex((post) => !post.draft)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="dark:bg-gray-800">
          <div className="content">
            <ol
              className="grid gap-4"
              style={{
                gridTemplateColumns: 'repeat(auto-fit, minmax(18rem, 1fr))',
              }}
            >
              {posts.map((post: PostDataType, i) => {
                return (
                  <PostCard key={i} post={post} newest={i === newestIndex} />
                )
              })}
            </ol>
          </div>
        </div>
      </Layout>
    </div>
  )
}

export default Home
